#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

. ./cfg/hardware.conf

if [ "$1" == "--wep" ]; then
	airodump-ng -t WEP $WLAN
elif [ "$1" == "--wpa" ]; then
	airodump-ng -t WPA -t WPA2 $WLAN
elif [ "$1" == "--help" ]; then
	echo "Options:"
	echo "--wep - Show only WEP access points"
	echo "--wpa - Show only WPA access points"
	echo "--all - Show all access points (default)"
else
	airodump-ng $WLAN
fi
