#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if [ -f ../cfg/target.conf ]; then
	. ../cfg/target.conf
else
	echo "Error: No target set!"
	exit 1
fi

ifconfig $WLAN down
iwconfig $WLAN mode managed
ifconfig $WLAN up
iwconfig $WLAN channel $CHANNEL
ifconfig $WLAN down
iwconfig $WLAN mode monitor
ifconfig $WLAN up

. ../cfg/hardware.conf

airodump-ng -c $CHANNEL --bssid $BSSID -w /tmp/psk $WLAN
